apiVersion: v1
description: A Jira-Server Helm chart for Kubernetes
name: jira
version: 1.1.0
home: https://ohanainfo.atlassian.net
maintainers:
  - name: "@ricardo-silva"
    email: ohanainfo@gmail.com

