apiVersion: v1
kind: Service
metadata:
  name: jira-lb
  labels:
    app: jira
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    ingress.kubernetes.io/affinity: cookie
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-name: route
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: web
    targetPort: 8080
  selector:
    app: jira
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
