apiVersion: v1
kind: PersistentVolume
metadata:
  name: jiradc-pv
spec:
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
#Specify the IP and sharedhome name defined on the Filestore
  nfs:
    path: /sharedhome
    server: 10.176.201.50
